- name: pypi-publish

on:
  push:
    branches:
    - main
    - python
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

  # You may pin to the exact commit or the version.
  # uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
  uses: pypa/gh-action-pypi-publish@v1.4.2
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
    # The repository URL to use
    repository_url: # optional
    # The target directory for distribution
    packages_dir: # optional, default is dist
    # Check metadata before uploading
    verify_metadata: # optional, default is true
    # Do not fail if a Python package distribution exists in the target package index
    skip_existing: # optional
    # Show verbose output.
    verbose: # optional
